package me.aov.sellgui.handlers

import me.aov.sellgui.SellGUIMain
import org.bukkit.Sound
import org.bukkit.entity.Player
import java.util.Locale

object SoundHandler {
    private const val FALLBACK_SOUND = "BLOCK_NOTE_BLOCK_BASS"
    private val soundKeys = mapOf("UI_BUTTON_CLICK" to "minecraft:ui.button.click", "BLOCK_NOTE_BLOCK_PLING" to "minecraft:block.note_block.pling", "BLOCK_NOTE_BLOCK_BASS" to "minecraft:block.note_block.bass", "ENTITY_EXPERIENCE_ORB_PICKUP" to "minecraft:entity.experience_orb.pickup", "ENTITY_PLAYER_LEVELUP" to "minecraft:entity.player.levelup", "ENTITY_VILLAGER_YES" to "minecraft:entity.villager.yes", "ENTITY_VILLAGER_NO" to "minecraft:entity.villager.no", "BLOCK_ANVIL_LAND" to "minecraft:block.anvil.land", "BLOCK_CHEST_OPEN" to "minecraft:block.chest.open", "BLOCK_CHEST_CLOSE" to "minecraft:block.chest.close", "ENTITY_ITEM_PICKUP" to "minecraft:entity.item.pickup", "ENTITY_FIREWORK_ROCKET_BLAST" to "minecraft:entity.firework_rocket.blast", "ENTITY_FIREWORK_ROCKET_LAUNCH" to "minecraft:entity.firework_rocket.launch", "ITEM_BOOK_PAGE_TURN" to "minecraft:item.book.page_turn")
    private val soundNamesByKey = soundKeys.flatMap { (name, key) -> listOf(key to name, key.removePrefix("minecraft:") to name) }.toMap()
    @JvmStatic fun getSafeSound(soundName: String?): Sound? = resolveSound(soundName) ?: resolveSound(FALLBACK_SOUND)
    @JvmStatic fun playSound(player: Player?, soundName: String?, volume: Float, pitch: Float) { player ?: return; try { val sound = resolveSound(soundName); val key = sound?.let { getSoundKey(it, soundName) } ?: toSoundKey(soundName); if (key != null) player.playSound(player.location, key, volume, pitch) else getSafeSound(soundName)?.let { player.playSound(player.location, it, volume, pitch) } } catch (_: Exception) { } catch (_: LinkageError) { } }
    @JvmStatic fun playSound(player: Player?, soundName: String?) = playSound(player, soundName, 1f, 1f)
    @JvmStatic fun playConfigSound(player: Player?, configPath: String) { player ?: return; try { val config = SellGUIMain.getInstance()?.configManager?.soundsConfig ?: return; if (!config.getBoolean("sounds.enabled", true) || !config.getBoolean("$configPath.enabled", true)) return; playSound(player, config.getString("$configPath.sound", "BLOCK_NOTE_BLOCK_PLING"), config.getDouble("$configPath.volume", 1.0).toFloat(), config.getDouble("$configPath.pitch", 1.0).toFloat()) } catch (_: Exception) { playSound(player, "BLOCK_NOTE_BLOCK_PLING", 1f, 1f) } }
    @JvmStatic fun playUIClick(player: Player?) = playConfigSound(player, "sounds.ui.button_click"); @JvmStatic fun playSuccess(player: Player?) = playConfigSound(player, "sounds.feedback.success"); @JvmStatic fun playError(player: Player?) = playConfigSound(player, "sounds.feedback.error"); @JvmStatic fun playPling(player: Player?) = playSound(player, "BLOCK_NOTE_BLOCK_PLING", 1f, 1f); @JvmStatic fun playBass(player: Player?) = playSound(player, "BLOCK_NOTE_BLOCK_BASS", 1f, 1f); @JvmStatic fun playFirework(player: Player?) = playSound(player, "ENTITY_FIREWORK_ROCKET_BLAST", 1f, 1f); @JvmStatic fun playItemPickup(player: Player?) = playConfigSound(player, "sounds.items.pickup"); @JvmStatic fun playChestOpen(player: Player?) = playConfigSound(player, "sounds.gui.open"); @JvmStatic fun playChestClose(player: Player?) = playConfigSound(player, "sounds.gui.close"); @JvmStatic fun playNoItemsSound(player: Player?, configuredSound: String?, volume: Float, pitch: Float) = playSound(player, configuredSound, volume, pitch)
    private fun resolveSound(soundName: String?): Sound? { if (soundName.isNullOrBlank()) return null; val normalized = normalizeSoundName(soundName); return resolveBukkitSound(soundNamesByKey[normalizeSoundKey(soundName)]) ?: resolveBukkitSound(normalized.removePrefix("MINECRAFT_")) ?: resolveBukkitSound(normalized) }
    private fun resolveBukkitSound(name: String?): Sound? = try { name?.let { Sound.valueOf(it) } } catch (_: IllegalArgumentException) { null } catch (_: LinkageError) { null }
    private fun getSoundKey(sound: Sound, configuredName: String?): String? = try { sound.key.toString() } catch (_: LinkageError) { toSoundKey(configuredName) }
    private fun toSoundKey(soundName: String?): String? { if (soundName.isNullOrBlank()) return soundKeys[FALLBACK_SOUND]; val trimmed = soundName.trim(); return soundKeys[normalizeSoundName(trimmed)] ?: if (trimmed.contains(':') || trimmed.contains('.')) trimmed.lowercase(Locale.ROOT) else "minecraft:${trimmed.lowercase(Locale.ROOT).replace('_', '.')}" }
    private fun normalizeSoundName(value: String): String = value.trim().uppercase().replace(":", "_").replace(".", "_").replace("-", "_").replace(" ", "_")
    private fun normalizeSoundKey(value: String?): String = value?.trim()?.lowercase(Locale.ROOT) ?: ""
}
