name: SellGUI
version: 2.0-SNAPSHOT
api-version: 1.16
author: Aov,SaneNuyan
main: me.aov.sellgui.SellGUIMain
depend: [Vault]
softdepend: [Essentials,MMOItems]
commands:
  sellgui:
    description: SellGUI Command
    usage: /sellgui
    permission: sellgui.use
  sellgui.mmoitems:
    description: Opens the MMOItems Price Editor
    usage: /sellgui
  sellall:
    description: Sells All Items in Inventory
    usage: /sellall
    permission: sellgui.sellall
permissions:
  sellgui.reload:
    description: Allows you to use /sellgui reload
  sellgui.createsign:
    description: Allows you to create a sign
  sellgui.usesign:
    description: Allows you to use a SellGUI sign
  sellgui.sellall:
    description: Allows you to Sell your Inventory Items
  sellgui.others:
    description: Allows you to open the SellGUI for others
