name: SellGUI
version: 2.2-SNAPSHOT
api-version: 1.21
author: Aov,SaneNuyan
main: me.aov.sellgui.SellGUIMain
depend: [Vault]
softdepend: [Essentials,MMOItems]
commands:
  sellgui:
    description: SellGUI Command
    usage: /sellgui [reload|<playername>]
  sellall:
    description: Sells All Items in Inventory
    usage: /sellall
    permission: sellgui.sellall
permissions:
  sellgui.reload:
    description: Allows you to use /sellgui reload
    default: op
  sellgui.createsign:
    description: Allows you to create a SellGUI sign
    default: op
  sellgui.usesign:
    description: Allows you to use a SellGUI sign
    default: true
  sellgui.sellall:
    description: Allows you to Sell your Inventory Items
    default: true
  sellgui.others:
    description: Allows you to open the SellGUI for other players
    default: op
  sellgui.use:
    description: Allows you to use /sellgui
    default: true