name: SellGUI
version: '2.9.1'
main: me.aov.sellgui.SellGUIMain
api-version: '1.20.6'
description: SellGUI plugin
author: AOOV,SaneNuyan
website: https://www.spigotmc.org/resources/sellgui.127355/

depend: [Vault]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - MMOItems
  - Essentials
  - Nexo
  - PlaceholderAPI
  - ShopGUIPlus
  - MythicLib
  - NBTAPI
  - packetevents
commands:
  autosell:
    description: Autosell GUI Command
    usage: /autosell
  sellgui:
    description: SellGUI
    usage: /sellgui [reload|setprice|evaluate|setrange|autosell|<playername>]
    aliases: [sg, sell]
  sellguiprice:
    description: Price Setter GUI Command
    usage: /sellguiprice
  sellall:
    description: Sell All Items Command
    usage: /sellall

permissions:
  sellgui.*:
    description: Gives access to all SellGUI commands and features
    children:
      sellgui.use: true
      sellgui.admin: true
      sellgui.setprice: true
      sellgui.setrange: true
      sellgui.evaluate: true
      sellgui.sellall: true
      sellgui.autosell: true # Added autosell permission
  sellgui.use:
    description: Allows player to use basic SellGUI features
    default: true
  sellgui.admin:
    description: Allows player to use admin commands
    default: op
  sellgui.setprice:
    description: Allows player to set custom prices on items
    default: op
  sellgui.setrange:
    description: Allows player to set custom random price ranges on items
    default: op
  sellgui.evaluate:
    description: Allows player to use price evaluation GUI
    default: op
  sellgui.sellall:
    description: Allows player to use sell all command
    default: true
  sellgui.reload:
    description: Allows player to reload the plugin
    default: op
  sellgui.bypass:
    description: Bypasses certain restrictions
    default: op
  sellgui.autosell: # New permission for autosell menu
    description: Allows player to open the autosell settings menu
    default: true
  sellgui.bonus.*:
    description: Permission-based bonus system
    default: false
  sellgui.multiplier.*:
    description: Permission-based multiplier system
    default: false

  # VIP rank permissions
  sellgui.vip:
    description: VIP rank - 1.5x sell multiplier
    default: false
  sellgui.premium:
    description: Premium rank - 2.0x sell multiplier
    default: false
  sellgui.elite:
    description: Elite rank - 3.0x sell multiplier
    default: false

  # Specific multiplier permissions
  sellgui.multiplier.1.2:
    description: 1.2x sell multiplier
    default: false
  sellgui.multiplier.1.5:
    description: 1.5x sell multiplier
    default: false
  sellgui.multiplier.2.0:
    description: 2.0x sell multiplier
    default: false
  sellgui.multiplier.2.5:
    description: 2.5x sell multiplier
    default: false
  sellgui.multiplier.3.0:
    description: 3.0x sell multiplier
    default: false
